/**
 * sanitizeOutput.js — central output sanitization boundary (missing-features #12).
 *
 * Imported/online lyrics and Bible text are untrusted input projected to the
 * room (projector + stream). All HTML that reaches a render boundary
 * (`dangerouslySetInnerHTML`, release notes, search snippets) must pass
 * through `sanitizeOutputHtml`. Plain-text lyric paths render via React text
 * nodes (auto-escaped) but still pass through `sanitizeOutputText` so the
 * boundary is explicit and control characters can never reach a display.
 *
 * LOCAL-WINS contract: legitimate content is byte-preserved —
 * translation brackets (`[Chorus]`), KJV/NASB translator brackets
 * (`[and he said]`), verse punctuation, `\n` line breaks, and full Unicode
 * (Yoruba, Spanish, etc.) all survive unchanged.
 *
 * Dependency-free strict allowlist (no new deps, lockfile untouched).
 * Default-deny: tags, attributes, and URL schemes not on the allowlist are
 * dropped. Unknown tags are unwrapped (children kept); known-dangerous
 * containers (script/style/iframe/…) are dropped WITH their content.
 */

const ALLOWED_TAGS = new Set([
  'a',
  'b',
  'blockquote',
  'br',
  'code',
  'del',
  'em',
  'h1',
  'h2',
  'h3',
  'hr',
  'i',
  'li',
  'mark',
  'ol',
  'p',
  'pre',
  's',
  'strike',
  'strong',
  'u',
  'ul',
]);

const VOID_TAGS = new Set(['br', 'hr']);

/** Tags whose entire subtree is dropped (tag + inner content). */
const DROP_WITH_CONTENT = new Set([
  'applet',
  'area',
  'audio',
  'base',
  'basefont',
  'button',
  'canvas',
  'embed',
  'fieldSet',
  'fieldset',
  'form',
  'frame',
  'frameset',
  'input',
  'label',
  'legend',
  'link',
  'map',
  'math',
  'meta',
  'noembed',
  'noframes',
  'noscript',
  'object',
  'optgroup',
  'option',
  'param',
  'picture',
  'script',
  'select',
  'slot',
  'source',
  'style',
  'svg',
  'template',
  'textarea',
  'title',
  'track',
  'video',
  'xmp',
  'listing',
  'plaintext',
  'marquee',
  'blink',
  'portal',
]);

const NAMED_ENTITIES = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  colon: ':',
  semi: ';',
  lpar: '(',
  rpar: ')',
  tab: '\t',
  newline: '\n',
 NewLine: '\n',
};

function decodeHtmlEntitiesOnce(value) {
  return String(value).replace(
    /&(#\d+|#[xX][0-9a-fA-F]+|[a-zA-Z]+);/g,
    (match, entity) => {
      if (entity[0] === '#') {
        const code =
          entity[1] === 'x' || entity[1] === 'X'
            ? parseInt(entity.slice(2), 16)
            : parseInt(entity.slice(1), 10);
        if (!Number.isFinite(code) || code < 0 || code > 0x10ffff) return match;
        try {
          return String.fromCodePoint(code);
        } catch {
          return match;
        }
      }
      return Object.prototype.hasOwnProperty.call(NAMED_ENTITIES, entity)
        ? NAMED_ENTITIES[entity]
        : match;
    },
  );
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (ch) => {
    switch (ch) {
      case '&':
        return '&amp;';
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      case '"':
        return '&quot;';
      default:
        return '&#39;';
    }
  });
}

/**
 * True only for navigation-safe link targets: http/https/mailto, or relative
 * references (anchors, paths, queries). Entity-encoded and whitespace-padded
 * `javascript:`/`data:`/`vbscript:` smuggling is neutralized by decoding and
 * stripping ASCII controls/whitespace before the scheme check (browsers
 * ignore those characters inside schemes too, so the check mirrors parsing).
 */
export function isSafeHref(raw) {
  if (typeof raw !== 'string') return false;
  const decoded = decodeHtmlEntitiesOnce(raw);
  const compact = decoded.replace(/[\x00-\x20\x7F]+/g, '');
  const url = compact.trim();
  if (!url) return false;
  const schemeMatch = url.match(/^([A-Za-z][A-Za-z0-9+.-]*):/);
  if (schemeMatch) {
    const scheme = schemeMatch[1].toLowerCase();
    return scheme === 'http' || scheme === 'https' || scheme === 'mailto';
  }
  if (url.startsWith('//')) return false;
  if (/[\s<>"]/.test(url)) return false;
  return true;
}

const UNSAFE_STYLE_PATTERN =
  /expression\s*\(|javascript\s*:|vbscript\s*:|behaviou?r\s*:|-moz-binding|url\s*\(|@import|<\/?|&#/i;

/**
 * Keep only `prop: value` declarations with a plain property name and no
 * dangerous constructs. Preserves the static typographic styles generated by
 * `markdownParser.convertMarkdownToHTML` while dropping `expression()` /
 * `url()` / `javascript:` vectors.
 */
export function sanitizeStyleValue(raw) {
  if (raw == null) return '';
  // Decode first: browsers entity-decode style attributes before CSS parsing.
  const value = decodeHtmlEntitiesOnce(String(raw));
  const kept = [];
  for (const declaration of value.split(';')) {
    const colon = declaration.indexOf(':');
    if (colon === -1) continue;
    const prop = declaration.slice(0, colon).trim().toLowerCase();
    const val = declaration.slice(colon + 1).trim();
    if (!prop || !val) continue;
    if (!/^[a-z][a-z-]*$/.test(prop)) continue;
    if (UNSAFE_STYLE_PATTERN.test(`${prop}:${val}`)) continue;
    kept.push(`${prop}: ${val}`);
  }
  return kept.join('; ');
}

function parseAttributes(source) {
  const attrs = [];
  const text = String(source || '').replace(/\/\s*$/, '');
  let k = 0;
  while (k < text.length) {
    while (k < text.length && /\s/.test(text[k])) k += 1;
    if (k >= text.length) break;
    if (text[k] === '/') {
      k += 1;
      continue;
    }
    const nameMatch = text.slice(k).match(/^([^\s=/>\"']+)/);
    if (!nameMatch) break;
    const name = nameMatch[1].toLowerCase();
    k += nameMatch[1].length;
    while (k < text.length && /\s/.test(text[k])) k += 1;
    let value = null;
    if (text[k] === '=') {
      k += 1;
      while (k < text.length && /\s/.test(text[k])) k += 1;
      const quote = text[k];
      if (quote === '"' || quote === "'") {
        k += 1;
        const end = text.indexOf(quote, k);
        if (end === -1) {
          value = text.slice(k);
          k = text.length;
        } else {
          value = text.slice(k, end);
          k = end + 1;
        }
      } else {
        const valueMatch = text.slice(k).match(/^[^\s>\"']*/);
        value = valueMatch ? valueMatch[0] : '';
        k += value.length;
      }
    }
    attrs.push([name, value]);
  }
  return attrs;
}

function buildAllowedTag(tagName, attrs) {
  if (VOID_TAGS.has(tagName)) return `<${tagName}>`;
  let extra = '';
  for (const [name, value] of attrs) {
    if (name === 'style' && value != null) {
      const clean = sanitizeStyleValue(value);
      if (clean) extra += ` style="${escapeHtml(clean)}"`;
    } else if (name === 'title' && value != null) {
      extra += ` title="${escapeHtml(value)}"`;
    } else if (tagName === 'a' && name === 'href' && value != null) {
      if (isSafeHref(value)) extra += ` href="${escapeHtml(value.trim())}"`;
    }
    // All other attributes (event handlers, src/srcset, data-*, id, class,
    // form attributes, …) are default-deny: dropped silently.
  }
  if (tagName === 'a') extra += ' target="_blank" rel="noopener noreferrer"';
  return `<${tagName}${extra}>`;
}

/**
 * Strict-allowlist HTML sanitizer. Returns safe HTML for render boundaries
 * (`dangerouslySetInnerHTML`). Plain text without markup passes through
 * entity-escaped (so `3 < 4` and `[Chorus]` survive as visible text).
 */
export function sanitizeOutputHtml(input) {
  if (input == null) return '';
  const html = String(input);
  if (!html) return '';
  let out = '';
  let i = 0;
  const len = html.length;
  const dropStack = [];

  while (i < len) {
    const ch = html[i];
    if (ch !== '<') {
      const next = html.indexOf('<', i);
      const end = next === -1 ? len : next;
      if (dropStack.length === 0) out += escapeHtml(html.slice(i, end));
      i = end;
      continue;
    }
    const nxt = html[i + 1];
    if (nxt === undefined || !/[a-zA-Z/!?]/.test(nxt)) {
      // Bare `<` (lyric math/comparisons like `3 < 4`): literal text.
      if (dropStack.length === 0) out += '&lt;';
      i += 1;
      continue;
    }
    if (nxt === '!') {
      if (html.startsWith('<!--', i)) {
        const end = html.indexOf('-->', i + 4);
        i = end === -1 ? len : end + 3;
      } else {
        const end = html.indexOf('>', i + 2);
        i = end === -1 ? len : end + 1;
      }
      continue;
    }
    if (nxt === '?') {
      const end = html.indexOf('>', i + 2);
      i = end === -1 ? len : end + 1;
      continue;
    }

    // Find `>` respecting quoted attribute values.
    let j = i + 1;
    let quote = null;
    while (j < len) {
      const c = html[j];
      if (quote) {
        if (c === quote) quote = null;
      } else if (c === '"' || c === "'") {
        quote = c;
      } else if (c === '>') {
        break;
      }
      j += 1;
    }
    if (j >= len) {
      // Unterminated tag: escape the remainder as text.
      if (dropStack.length === 0) out += escapeHtml(html.slice(i));
      break;
    }

    const tagSource = html.slice(i + 1, j);
    const isClose = tagSource.startsWith('/');
    const nameMatch = tagSource
      .slice(isClose ? 1 : 0)
      .match(/^\s*([a-zA-Z][a-zA-Z0-9]*)/);
    if (!nameMatch) {
      if (dropStack.length === 0) out += escapeHtml(html.slice(i, j + 1));
      i = j + 1;
      continue;
    }
    const tagName = nameMatch[1].toLowerCase();
    const rest = tagSource.slice(nameMatch[0].length);
    const selfClosing = /\/\s*$/.test(tagSource);

    if (isClose) {
      if (dropStack.length > 0) {
        if (dropStack[dropStack.length - 1] === tagName) dropStack.pop();
      } else if (ALLOWED_TAGS.has(tagName) && !VOID_TAGS.has(tagName)) {
        out += `</${tagName}>`;
      }
      i = j + 1;
      continue;
    }

    if (dropStack.length > 0) {
      if (DROP_WITH_CONTENT.has(tagName) && !VOID_TAGS.has(tagName) && !selfClosing) {
        dropStack.push(tagName);
      }
      i = j + 1;
      continue;
    }
    if (DROP_WITH_CONTENT.has(tagName)) {
      if (!VOID_TAGS.has(tagName) && !selfClosing) dropStack.push(tagName);
      i = j + 1;
      continue;
    }
    if (!ALLOWED_TAGS.has(tagName)) {
      // Unwrap: drop the tag, keep children (legit text is never lost).
      i = j + 1;
      continue;
    }
    out += buildAllowedTag(tagName, parseAttributes(rest));
    i = j + 1;
  }
  return out;
}

/**
 * Plain-text output boundary. Identity for legitimate lyric/Bible content
 * (brackets, punctuation, line breaks, Unicode) — strips only C0 controls /
 * DEL that can never be legitimate display text. React text rendering already
 * escapes markup; this keeps the boundary explicit and total.
 */
export function sanitizeOutputText(value) {
  if (value == null) return '';
  return String(value).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '');
}

/**
 * Output-route slug boundary for DynamicOutputRoute. Mirrors
 * `slugifyOutputName` (lowercase `[a-z0-9-]` plus legacy `_`); anything else
 * resolves to '' so the route renders OutputNotFound instead of hitting the
 * resolver with attacker-controlled input.
 */
export function sanitizeOutputSlug(value) {
  const slug = String(value ?? '')
    .replace(/^\/+/, '')
    .trim()
    .toLowerCase();
  if (!slug || slug === '.' || slug === '..') return '';
  if (!/^[a-z0-9][a-z0-9-_]*$/.test(slug)) return '';
  return slug;
}

export const SANITIZE_OUTPUT_ALLOWLIST = Object.freeze({
  tags: Object.freeze([...ALLOWED_TAGS]),
  linkSchemes: Object.freeze(['http', 'https', 'mailto']),
});
