#!/usr/bin/env node
/**
 * speech-engine/index.js — executable entry point for the LyricDisplay
 * speech engine (Phase 2 scaffold).
 *
 * Usage:
 *   node index.js [--engine=fake|whisper] [--host=127.0.0.1] [--port=4731]
 *
 * Environment (set by LyricDisplay's supervisor when it forks us):
 *   LD_SPEECH_TOKEN   per-launch secret required on every request (REQUIRED
 *                     — generated by the supervisor; never printed here)
 *   LD_SPEECH_HOST    bind host, loopback only (default 127.0.0.1)
 *   LD_SPEECH_PORT    bind port, 0 = ephemeral (default 4731)
 *   LD_SPEECH_ENGINE  engine kind (default fake)
 *
 * Modes:
 *   fake     (default) canned engine from fakeEngine.js — no model, no
 *            binary, no download. This is what makes Phase 2 verifiable.
 *   whisper  NOT WIRED YET. Exits with a clear message; the native
 *            whisper.cpp binding is a machine-verified follow-up. Nothing
 *            in this repository requires it to pass its tests.
 *
 * Security invariants enforced here and in server.js:
 *   - binds loopback ONLY (assertLoopbackBindHost throws otherwise)
 *   - token required on every request
 *   - the token is NEVER logged or printed, not even on startup
 *
 * Process protocol (fork IPC, mirrored from main/backend.js):
 *   parent <- { status: 'ready', host, port, apiVersion }
 *   parent <- { status: 'error', error: 'EADDRINUSE', port }
 *   parent <- { t, ... }  message-bus mirror (see bus.js)
 */
import { generateEngineToken, SPEECH_PROTOCOL_VERSION } from '../shared/speech/protocol.js';
import { createSpeechEngineServer, DEFAULT_BIND_HOST } from './server.js';
import { createFakeEngine } from './fakeEngine.js';
import { createMessageBus } from './bus.js';

function parseArgs(argv) {
  const out = {};
  for (const arg of argv) {
    const match = /^--([a-zA-Z-]+)(?:=(.*))?$/.exec(arg);
    if (match) out[match[1]] = match[2] === undefined ? true : match[2];
  }
  return out;
}

const args = parseArgs(process.argv.slice(2));
const env = process.env;

const engineKind = String(args.engine ?? env.LD_SPEECH_ENGINE ?? 'fake');
if (engineKind !== 'fake') {
  // Honest failure: no native binary exists yet, and we must never fake a
  // whisper run as if it were real transcription.
  console.error(
    `speech-engine: engine "${engineKind}" is not wired yet — the native whisper.cpp binding is ` +
      'a follow-up. Run with --engine=fake (default) for the canned engine.'
  );
  process.exit(2);
}

const host = String(args.host ?? env.LD_SPEECH_HOST ?? DEFAULT_BIND_HOST);
const port = Number(args.port ?? env.LD_SPEECH_PORT ?? 4731);
const token = typeof args.token === 'string' && args.token.length >= 16
  ? args.token
  : (typeof env.LD_SPEECH_TOKEN === 'string' && env.LD_SPEECH_TOKEN.length >= 16
      ? env.LD_SPEECH_TOKEN
      : generateEngineToken());

const bus = createMessageBus();

// Parent-process mirror: LyricDisplay's supervisor subscribes over the fork
// IPC channel and relays recognized messages to the renderer. This is the
// Phase 2 substitute for the WebSocket transport — same bus, different sink.
bus.subscribe((message) => {
  if (typeof process.send === 'function') {
    try {
      process.send(message);
    } catch {
      // Parent went away; the HTTP surface keeps serving.
    }
  }
});

const handle = createSpeechEngineServer({
  token,
  host,
  bus,
  engine: createFakeEngine({ bus }),
});

const shutdown = () => {
  handle
    .close()
    .catch(() => {})
    .finally(() => process.exit(0));
  // Safety net: never hang a shutdown the supervisor is escalating.
  setTimeout(() => process.exit(0), 1000).unref();
};

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

handle
  .listen(port, host)
  .then(({ port: boundPort, host: boundHost }) => {
    // No token in this line — logs must never carry secrets.
    console.log(`speech-engine [fake] listening on http://${boundHost}:${boundPort}`);
    if (typeof process.send === 'function') {
      process.send({ status: 'ready', host: boundHost, port: boundPort, apiVersion: SPEECH_PROTOCOL_VERSION });
    }
  })
  .catch((error) => {
    if (error?.code === 'EADDRINUSE') {
      if (typeof process.send === 'function') {
        process.send({ status: 'error', error: 'EADDRINUSE', port });
      }
      console.error(`speech-engine: port ${port} is already in use`);
      process.exit(1);
    }
    // Loopback refusal and bind failures land here, loudly and non-zero.
    console.error(`speech-engine: failed to start: ${error.message}`);
    if (typeof process.send === 'function') {
      process.send({ status: 'error', error: error.code || 'bind-failed', message: error.message });
    }
    process.exit(1);
  });
